/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as Kyc_verificationRouteImport } from './routes/kyc_verification'
import { Route as AlgoRregistrationRouteImport } from './routes/algoRregistration'
import { Route as UserRouteImport } from './routes/_user'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperAdminDashboardRouteImport } from './routes/super-admin/dashboard'
import { Route as SuperAdminCreatestrategiesRouteImport } from './routes/super-admin/createstrategies'
import { Route as DhanCallbackRouteImport } from './routes/dhan/callback'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminErrorsRouteImport } from './routes/admin/errors'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminClientsRouteImport } from './routes/admin/clients'
import { Route as UserProfileRouteImport } from './routes/_user/profile'
import { Route as UserPositionsRouteImport } from './routes/_user/positions'
import { Route as UserPortfolioRouteImport } from './routes/_user/portfolio'
import { Route as UserOrdersRouteImport } from './routes/_user/orders'
import { Route as UserMoneyRouteImport } from './routes/_user/money'
import { Route as UserDashboardRouteImport } from './routes/_user/dashboard'
import { Route as ResetPasswordUidTokenRouteImport } from './routes/reset-password.$uid.$token'
import { Route as AdminClientIdRouteImport } from './routes/admin/client/$id'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const Kyc_verificationRoute = Kyc_verificationRouteImport.update({
  id: '/kyc_verification',
  path: '/kyc_verification',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgoRregistrationRoute = AlgoRregistrationRouteImport.update({
  id: '/algoRregistration',
  path: '/algoRregistration',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRoute = UserRouteImport.update({
  id: '/_user',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminDashboardRoute = SuperAdminDashboardRouteImport.update({
  id: '/super-admin/dashboard',
  path: '/super-admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminCreatestrategiesRoute =
  SuperAdminCreatestrategiesRouteImport.update({
    id: '/super-admin/createstrategies',
    path: '/super-admin/createstrategies',
    getParentRoute: () => rootRouteImport,
  } as any)
const DhanCallbackRoute = DhanCallbackRouteImport.update({
  id: '/dhan/callback',
  path: '/dhan/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminErrorsRoute = AdminErrorsRouteImport.update({
  id: '/admin/errors',
  path: '/admin/errors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/admin/clients',
  path: '/admin/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UserRoute,
} as any)
const UserPositionsRoute = UserPositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => UserRoute,
} as any)
const UserPortfolioRoute = UserPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => UserRoute,
} as any)
const UserOrdersRoute = UserOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => UserRoute,
} as any)
const UserMoneyRoute = UserMoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => UserRoute,
} as any)
const UserDashboardRoute = UserDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => UserRoute,
} as any)
const ResetPasswordUidTokenRoute = ResetPasswordUidTokenRouteImport.update({
  id: '/reset-password/$uid/$token',
  path: '/reset-password/$uid/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientIdRoute = AdminClientIdRouteImport.update({
  id: '/admin/client/$id',
  path: '/admin/client/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/algoRregistration': typeof AlgoRregistrationRoute
  '/kyc_verification': typeof Kyc_verificationRoute
  '/register': typeof RegisterRoute
  '/signin': typeof SigninRoute
  '/dashboard': typeof UserDashboardRoute
  '/money': typeof UserMoneyRoute
  '/orders': typeof UserOrdersRoute
  '/portfolio': typeof UserPortfolioRoute
  '/positions': typeof UserPositionsRoute
  '/profile': typeof UserProfileRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/errors': typeof AdminErrorsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/profile': typeof AdminProfileRoute
  '/dhan/callback': typeof DhanCallbackRoute
  '/super-admin/createstrategies': typeof SuperAdminCreatestrategiesRoute
  '/super-admin/dashboard': typeof SuperAdminDashboardRoute
  '/admin/client/$id': typeof AdminClientIdRoute
  '/reset-password/$uid/$token': typeof ResetPasswordUidTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/algoRregistration': typeof AlgoRregistrationRoute
  '/kyc_verification': typeof Kyc_verificationRoute
  '/register': typeof RegisterRoute
  '/signin': typeof SigninRoute
  '/dashboard': typeof UserDashboardRoute
  '/money': typeof UserMoneyRoute
  '/orders': typeof UserOrdersRoute
  '/portfolio': typeof UserPortfolioRoute
  '/positions': typeof UserPositionsRoute
  '/profile': typeof UserProfileRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/errors': typeof AdminErrorsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/profile': typeof AdminProfileRoute
  '/dhan/callback': typeof DhanCallbackRoute
  '/super-admin/createstrategies': typeof SuperAdminCreatestrategiesRoute
  '/super-admin/dashboard': typeof SuperAdminDashboardRoute
  '/admin/client/$id': typeof AdminClientIdRoute
  '/reset-password/$uid/$token': typeof ResetPasswordUidTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_user': typeof UserRouteWithChildren
  '/algoRregistration': typeof AlgoRregistrationRoute
  '/kyc_verification': typeof Kyc_verificationRoute
  '/register': typeof RegisterRoute
  '/signin': typeof SigninRoute
  '/_user/dashboard': typeof UserDashboardRoute
  '/_user/money': typeof UserMoneyRoute
  '/_user/orders': typeof UserOrdersRoute
  '/_user/portfolio': typeof UserPortfolioRoute
  '/_user/positions': typeof UserPositionsRoute
  '/_user/profile': typeof UserProfileRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/errors': typeof AdminErrorsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/profile': typeof AdminProfileRoute
  '/dhan/callback': typeof DhanCallbackRoute
  '/super-admin/createstrategies': typeof SuperAdminCreatestrategiesRoute
  '/super-admin/dashboard': typeof SuperAdminDashboardRoute
  '/admin/client/$id': typeof AdminClientIdRoute
  '/reset-password/$uid/$token': typeof ResetPasswordUidTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/algoRregistration'
    | '/kyc_verification'
    | '/register'
    | '/signin'
    | '/dashboard'
    | '/money'
    | '/orders'
    | '/portfolio'
    | '/positions'
    | '/profile'
    | '/admin/clients'
    | '/admin/dashboard'
    | '/admin/errors'
    | '/admin/orders'
    | '/admin/profile'
    | '/dhan/callback'
    | '/super-admin/createstrategies'
    | '/super-admin/dashboard'
    | '/admin/client/$id'
    | '/reset-password/$uid/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/algoRregistration'
    | '/kyc_verification'
    | '/register'
    | '/signin'
    | '/dashboard'
    | '/money'
    | '/orders'
    | '/portfolio'
    | '/positions'
    | '/profile'
    | '/admin/clients'
    | '/admin/dashboard'
    | '/admin/errors'
    | '/admin/orders'
    | '/admin/profile'
    | '/dhan/callback'
    | '/super-admin/createstrategies'
    | '/super-admin/dashboard'
    | '/admin/client/$id'
    | '/reset-password/$uid/$token'
  id:
    | '__root__'
    | '/'
    | '/_user'
    | '/algoRregistration'
    | '/kyc_verification'
    | '/register'
    | '/signin'
    | '/_user/dashboard'
    | '/_user/money'
    | '/_user/orders'
    | '/_user/portfolio'
    | '/_user/positions'
    | '/_user/profile'
    | '/admin/clients'
    | '/admin/dashboard'
    | '/admin/errors'
    | '/admin/orders'
    | '/admin/profile'
    | '/dhan/callback'
    | '/super-admin/createstrategies'
    | '/super-admin/dashboard'
    | '/admin/client/$id'
    | '/reset-password/$uid/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UserRoute: typeof UserRouteWithChildren
  AlgoRregistrationRoute: typeof AlgoRregistrationRoute
  Kyc_verificationRoute: typeof Kyc_verificationRoute
  RegisterRoute: typeof RegisterRoute
  SigninRoute: typeof SigninRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminErrorsRoute: typeof AdminErrorsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProfileRoute: typeof AdminProfileRoute
  DhanCallbackRoute: typeof DhanCallbackRoute
  SuperAdminCreatestrategiesRoute: typeof SuperAdminCreatestrategiesRoute
  SuperAdminDashboardRoute: typeof SuperAdminDashboardRoute
  AdminClientIdRoute: typeof AdminClientIdRoute
  ResetPasswordUidTokenRoute: typeof ResetPasswordUidTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc_verification': {
      id: '/kyc_verification'
      path: '/kyc_verification'
      fullPath: '/kyc_verification'
      preLoaderRoute: typeof Kyc_verificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algoRregistration': {
      id: '/algoRregistration'
      path: '/algoRregistration'
      fullPath: '/algoRregistration'
      preLoaderRoute: typeof AlgoRregistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user': {
      id: '/_user'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/dashboard': {
      id: '/super-admin/dashboard'
      path: '/super-admin/dashboard'
      fullPath: '/super-admin/dashboard'
      preLoaderRoute: typeof SuperAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/createstrategies': {
      id: '/super-admin/createstrategies'
      path: '/super-admin/createstrategies'
      fullPath: '/super-admin/createstrategies'
      preLoaderRoute: typeof SuperAdminCreatestrategiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dhan/callback': {
      id: '/dhan/callback'
      path: '/dhan/callback'
      fullPath: '/dhan/callback'
      preLoaderRoute: typeof DhanCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/errors': {
      id: '/admin/errors'
      path: '/admin/errors'
      fullPath: '/admin/errors'
      preLoaderRoute: typeof AdminErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/admin/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user/profile': {
      id: '/_user/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/positions': {
      id: '/_user/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof UserPositionsRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/portfolio': {
      id: '/_user/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof UserPortfolioRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/orders': {
      id: '/_user/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof UserOrdersRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/money': {
      id: '/_user/money'
      path: '/money'
      fullPath: '/money'
      preLoaderRoute: typeof UserMoneyRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/dashboard': {
      id: '/_user/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof UserDashboardRouteImport
      parentRoute: typeof UserRoute
    }
    '/reset-password/$uid/$token': {
      id: '/reset-password/$uid/$token'
      path: '/reset-password/$uid/$token'
      fullPath: '/reset-password/$uid/$token'
      preLoaderRoute: typeof ResetPasswordUidTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/client/$id': {
      id: '/admin/client/$id'
      path: '/admin/client/$id'
      fullPath: '/admin/client/$id'
      preLoaderRoute: typeof AdminClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface UserRouteChildren {
  UserDashboardRoute: typeof UserDashboardRoute
  UserMoneyRoute: typeof UserMoneyRoute
  UserOrdersRoute: typeof UserOrdersRoute
  UserPortfolioRoute: typeof UserPortfolioRoute
  UserPositionsRoute: typeof UserPositionsRoute
  UserProfileRoute: typeof UserProfileRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserDashboardRoute: UserDashboardRoute,
  UserMoneyRoute: UserMoneyRoute,
  UserOrdersRoute: UserOrdersRoute,
  UserPortfolioRoute: UserPortfolioRoute,
  UserPositionsRoute: UserPositionsRoute,
  UserProfileRoute: UserProfileRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UserRoute: UserRouteWithChildren,
  AlgoRregistrationRoute: AlgoRregistrationRoute,
  Kyc_verificationRoute: Kyc_verificationRoute,
  RegisterRoute: RegisterRoute,
  SigninRoute: SigninRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminErrorsRoute: AdminErrorsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProfileRoute: AdminProfileRoute,
  DhanCallbackRoute: DhanCallbackRoute,
  SuperAdminCreatestrategiesRoute: SuperAdminCreatestrategiesRoute,
  SuperAdminDashboardRoute: SuperAdminDashboardRoute,
  AdminClientIdRoute: AdminClientIdRoute,
  ResetPasswordUidTokenRoute: ResetPasswordUidTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
